### ISSUE TITLE
On the meta-package - idea/discussion

### ISSUE THREAD

**Issue by Sobak** [phpdoctest/meta#1]
Hi,

referencing Current Ideas:

> And then create a meta-package that combines the english docs with the base-stuff
> 
> ```sh
> mkdir phpdoc-en
> cd phpdoc-en
> git init
> git submodule add git@github.com:phpdoctest/doc-base.git
> git submodule add git@github.com:phpdoctest/en.git
> git commit -m "Initial Commit"
> ```

The problem is,  git submodules always have to point specific commit. In other words: you cannot have such repo whose submodules are auto-updating - following example above: after any commit to either `doc-base` or `en` you need to update references in `phpdoc-en`. It seems like a no way to go.

**Comment by Sobak** [comment]
Thinking of the possible solutions: maybe we could add simple utility script in doc-base that would update this repo itself and also fetch/update any other languages fetched by its side? Let me show the workflow I'm talking about (on the *user's* side!)

```sh
mkdir phpdoc && cd phpdoc
git clone git@github.com:phpdoctest/doc-base.git
doc-base/get-lang.php en # or any other name, just talking about this potential script
```

And the structure created would be of course

```
phpdoc
|- doc-base
|- en
```

Same for updates, I think. E.g. invoking `get-lang.php` without parameters (or with languages which are already fetched) would perform `git pull` on those langs and doc-base itself.

I know it means more workflow for the contributors, but considering your currently suggested approach, I don't think we're able to handle it reliably on other side.

Thoughts anyone?

**Comment by heiglandreas** [comment]
I'd rather avoid submidules as the add an overhead that IMHO isn't necessary.

A "default" user can clone the language repo, make changes and open a PR. A CI-run then checks all the things necessary. That CI-run requires the doc-base but not the user.

A "power-user" knows a bit more and will be so knowledgeable that it's not an issue for them to checkout the doc-base as well as the language repo without them being directly connected via a submodule. It needs to be documented: Yes, I'm with you there!

There might even be a possibility to add a script to every repo that fetches the current version of doc-base and if it's not there, clones it right from the used git-server. 

So I don't really see a necessity to have them combined via submodules. Thad only adds overhead IMHO

**Comment by Sobak** [comment]
Fine, I like you general philosophy. I really do. Let me to leave it open for a while, if there are potential related issues to arise.

**Comment by Sobak** [comment]
I think it can be now closed. Woah, how the time flies - honestly I simply forgot that I commented on or even saw this repo months earlier :D
