### ISSUE TITLE
Create new git-repos on git.php.net

### ISSUE THREAD

**Issue by heiglandreas** [phpdoctest/meta#2]
We need at least the following new git repos on git.php.net

- [ ] doc-base
- [x] en

And then for each language that shall be moved one as well. That would currently mean the following:

- [ ] ar
- [ ] bg
- [ ] ca
- [ ] cs
- [ ] da
- [x] de
- [ ] el
- [ ] en
- [ ] es
- [ ] fa
- [ ] fi
- [ ] fr
- [ ] he
- [ ] hk
- [ ] hu
- [ ] id
- [ ] it
- [ ] ja
- [ ] kr
- [ ] lt
- [ ] nl
- [ ] no
- [ ] pl
- [ ] pt
- [ ] pt_BR
- [ ] ro
- [ ] ru
- [ ] sk
- [ ] sl
- [ ] sr
- [ ] sv
- [ ] tr
- [ ] tw
- [ ] uk
- [ ] zh

**Comment by heiglandreas** [comment]
@derickr was on that. He wrote to the systems-mailinglist but I don't know whether he got a response on that or not…

**Comment by heiglandreas** [comment]
I'd suggest a 5th "project"-folder `phpdocs`so that we'd get `phpdocs/doc-base` or `phpdocs/en`

**Comment by petk** [comment]
Hello, worth noting that there are some Git repositories created at https://git.php.net/ in the `doc` section.

**Comment by heiglandreas** [comment]
:smile: Yeah! Just this morning I tried to add exactly that information to this ticket but failed miserably on my phone.

There are repositories to test the whole setup with the english and the german docs, though the rest of the repos for the remaining docs still need to be created. And there is also no mirroring set up yet (AFAIK)
